---

- name: "Generate start file"
  template:
    src: "start.sh.j2"
    dest: "{{ compose_path }}/start-{{ app }}.sh"
    mode: "u=rwx,g=rwx,o=r"

- name: "Generate stop file"
  template:
    src: "stop.sh.j2"
    dest: "{{ compose_path }}/stop-{{ app }}.sh"
    mode: "u=rwx,g=rwx,o=r"